name: Deploy to DockerHub

on:
  push:
    branches:
      - main  # ✅ This triggers on push to main (including merges)


jobs:
  deploy:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3

      - name: Echo completion message
        run: echo "Successfully built and pushed Docker image to DockerHub!"

# 