name: Run Tests

on:
  pull_request:
    types: [opened,synchronize] # Triggers when a pull request is opened
    branches:
      - main # Specify the branch where PRs are opened against (e.g., main, master).

  # push:
  #   branches:
  #     - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm test